// This string is autogenerated by ChangeAppSettings.sh, do not change spaces amount
package org.onaips.supertux;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.Gravity;
import android.view.View;
import android.view.MotionEvent;
import android.view.KeyEvent;
import android.view.Window;
import android.view.WindowManager;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.os.PowerManager;
import android.widget.TextView;
import android.widget.Toast;
import android.app.AlertDialog;
import android.view.View.OnClickListener;


import org.onaips.supertux.DPadArrowOverlay;
import org.onaips.supertux.DifferentTouchInput;
import org.onaips.supertux.DifferentTouchInput.MultiTouchInput;

public class MainActivity extends Activity {
	public static int screenWidth;
	public static int screenHeight;
	private ProgressDialog  loadingDialog;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		screenHeight= getWindowManager().getDefaultDisplay().getHeight();
		screenWidth= getWindowManager().getDefaultDisplay().getWidth();


		// fullscreen mode
		requestWindowFeature(Window.FEATURE_NO_TITLE);
		getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
				WindowManager.LayoutParams.FLAG_FULLSCREEN); 

		_tv = new TextView(this);
		_tv.setText("Welcome to SuperTux!\n\nIf you just see this screen please restart app.");
		setContentView(_tv);
		//initSDL();

		startDownloader();

		//############################

		//Settings.Load(this);
		PowerManager pm = (PowerManager) getSystemService(Context.POWER_SERVICE);
		wakeLock = pm.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK, Globals.ApplicationName);
		wakeLock.acquire();


		mLoadLibraryStub = new LoadLibrary();
		mAudioThread = new AudioThread(this);
	}

	public void startDownloader()
	{
		if( downloader == null )
			downloader = new DataDownloader(this, _tv);
	}

	public void initSDL()
	{
		if(sdlInited)
			return;
		sdlInited = true;

		initJVM();

		mGLView = new DemoGLSurfaceView(this);

		// Create layout
		FrameLayout overlayLayout = new FrameLayout(this);
		overlayLayout.addView(mGLView);

		boolean isMultiTouch = DifferentTouchInput.getInstance() instanceof MultiTouchInput;
		if (isMultiTouch)
		{
			GradientDrawable dpadBg = new GradientDrawable();
			dpadBg.setShape(GradientDrawable.RECTANGLE);
			dpadBg.setColor(Color.argb(80, 0, 0, 0));
			dpadBg.setCornerRadius(24f);
			dpadBg.setStroke(2, Color.argb(150, 255, 255, 255));

			ImageView dpadView = new ImageView(this);
			dpadView.setBackgroundDrawable(dpadBg);

			DPadArrowOverlay arrowsView = new DPadArrowOverlay(this);

			FrameLayout dpadContainer = new FrameLayout(this);
			FrameLayout.LayoutParams containerParams = new FrameLayout.LayoutParams(MultiTouchInput.dpadSize, MultiTouchInput.dpadSize);
			containerParams.gravity = Gravity.BOTTOM | Gravity.LEFT;
			containerParams.leftMargin = 10;
			containerParams.bottomMargin = 10;
			dpadContainer.setLayoutParams(containerParams);

			dpadContainer.addView(dpadView, new FrameLayout.LayoutParams(MultiTouchInput.dpadSize, MultiTouchInput.dpadSize));
			dpadContainer.addView(arrowsView, new FrameLayout.LayoutParams(MultiTouchInput.dpadSize, MultiTouchInput.dpadSize));

			overlayLayout.addView(dpadContainer);
		}


		GradientDrawable jumpBg = new GradientDrawable();
		jumpBg.setShape(GradientDrawable.OVAL);
		jumpBg.setColor(Color.argb(100, 0, 200, 80));
		jumpBg.setStroke(3, Color.WHITE);

		ImageView jumpBtnView = new ImageView(this);
		jumpBtnView.setBackgroundDrawable(jumpBg);

		FrameLayout.LayoutParams jumpParams = new FrameLayout.LayoutParams(DifferentTouchInput.actionWidth, DifferentTouchInput.actionHeight);
		if (isMultiTouch)
		{
			jumpParams.gravity = Gravity.BOTTOM | Gravity.RIGHT;
			jumpParams.rightMargin = 20;
		}
		else
		{
			jumpParams.gravity = Gravity.BOTTOM | Gravity.LEFT;
			jumpParams.leftMargin = 20;
		}
		jumpParams.bottomMargin = 20;
		jumpBtnView.setLayoutParams(jumpParams);


		GradientDrawable runBg = new GradientDrawable();
		runBg.setShape(GradientDrawable.OVAL);
		runBg.setColor(Color.argb(100, 220, 50, 50));
		runBg.setStroke(3, Color.WHITE);

		ImageView runBtnView = new ImageView(this);
		runBtnView.setBackgroundDrawable(runBg);

		FrameLayout.LayoutParams runParams = new FrameLayout.LayoutParams(DifferentTouchInput.actionWidth, DifferentTouchInput.actionHeight);
		runParams.gravity = Gravity.BOTTOM | Gravity.RIGHT;
		runParams.rightMargin = isMultiTouch ? DifferentTouchInput.actionWidth + 40 : 20;
		runParams.bottomMargin = 20;
		runBtnView.setLayoutParams(runParams);


		overlayLayout.addView(jumpBtnView);
		overlayLayout.addView(runBtnView);
		setContentView(overlayLayout);


		// Receive keyboard events
		mGLView.setFocusableInTouchMode(true);
		mGLView.setFocusable(true);
		mGLView.requestFocus();
		/*PowerManager pm = (PowerManager) getSystemService(Context.POWER_SERVICE);
		wakeLock = pm.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK, Globals.ApplicationName);
		wakeLock.acquire();*/
	}

	@Override
	protected void onPause() {
		if( downloader != null ) {
			synchronized( downloader ) {
				downloader.setParent(null, null);
			}
		}
		// TODO: if application pauses it's screen is messed up
		if( wakeLock != null )
			wakeLock.release();
		super.onPause();
		if( mGLView != null )
			mGLView.onPause();
	}

	@Override
	protected void onResume() {
		if( wakeLock != null )
			wakeLock.acquire();
		super.onResume();
		if( mGLView != null )
			mGLView.onResume();
		if( downloader != null ) {
			synchronized( downloader ) {
				downloader.setParent(this, _tv);
				if( downloader.DownloadComplete )
					initSDL();
			}
		}
	}

	@Override
	protected void onStop() 
	{
		if( downloader != null ) {
			synchronized( downloader ) {
				downloader.setParent(null, null);
			}
		}
		if( wakeLock != null )
			wakeLock.release();

		if( mGLView != null )
			mGLView.exitApp();
		super.onStop();
		finish();
	}

	@Override
	public boolean onKeyDown(int keyCode, final KeyEvent event) {
		// Overrides Back key to use in our app
		if( mGLView != null )
			mGLView.nativeKey( keyCode, 1 );
		if( keyCode == KeyEvent.KEYCODE_BACK && !downloader.DownloadComplete )
			onStop();
		return true;
	}

	@Override
	public boolean onKeyUp(int keyCode, final KeyEvent event) {
		if( mGLView != null )
			mGLView.nativeKey( keyCode, 0 );
		return true;
	}

	@Override
	public boolean dispatchTouchEvent(final MotionEvent ev) {
		if(mGLView != null)
			mGLView.onTouchEvent(ev);
		return true;
	}

	public static native void initJVM();

	private DemoGLSurfaceView mGLView = null;
	private LoadLibrary mLoadLibraryStub = null;
	private AudioThread mAudioThread = null;
	private PowerManager.WakeLock wakeLock = null;
	private static DataDownloader downloader = null;
	private TextView _tv = null;
	private boolean sdlInited = false;
}
